# this test will just run terraform without salt

name: terraform end-to-end tests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master, develop ]
    paths:
     # build only for PR modifying libvirt and salt folders
      - 'libvirt/**'
      - 'salt/**'
      - 'pillar_examples/**'

jobs:
  # This workflow contains a single job called "build"
  terraform-deploy-netweaver-hana:
    # The type of runner that the job will run on
    runs-on: self-hosted 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: terraform apply netweaver and hana
      run: |
        cd libvirt
        # copy data for deploy
        cp /tmp/terraform.tfvars .
        terraform workspace new gh-terraform1
        terraform workspace select gh-terraform1
        terraform init
        terraform apply -auto-approve
        
     - name: terraform destroy
      run: |
        cd libvirt
        # copy data for deploy
        cp /tmp/terraform.tfvars .
        terraform workspace new gh-terraform1
        terraform workspace select gh-terraform1
        terraform init
        terraform destroy -auto-approve